# file: C:\Users\Lisardo Iniesta\AppData\Roaming\Python\Python313\site-packages\pydantic\errors.py
# hypothesis_version: 6.142.1

[".*'(.+?)'", 'PydanticErrorCodes', 'PydanticImportError', 'PydanticUserError', 'config-both', 'custom-json-schema', 'dataclass-on-model', 'discriminator-alias', 'import-error', 'invalid-self-type', 'removed-kwargs', 'root-model-extra', 'typed-dict-version', 'undefined-annotation', 'unpack-typed-dict', 'validate-call-type', 'validator-input-type', 'validator-no-fields', 'validator-signature', 'with-config-on-model']